### ISSUE TITLE
Define as a form-associated custom element

### ISSUE THREAD

**Issue by fonsp** [OM-MediaWorks/bcp47-picker#13]
Hey! A small enhancement would be to define the bcp47 element as a "form-associated custom element".

https://web.dev/articles/more-capable-form-controls#defining_a_form-associated_custom_element

This would allow for features including:
- Clicking a `<label>` element can focus the bcp47 picker
- A bcp47 picker included in a `<form>` will automatically be included in the form data
- A bcp47 picker included in a `<form>` can be reset when the form is reset

**Comment by danielbeeke** [comment]
Hi @fonsp I just did a release which contains this functionality.
Submitting a form now has the data of the bcp47-picker
