### ISSUE TITLE
Cannot blur by clicking outside the picker

### ISSUE THREAD

**Issue by fonsp** [OM-MediaWorks/bcp47-picker#8]
Hey! I love the BCP47 picker, super nice!

I noticed that you cannot blur the component by clicking outside of it, like you would expect from an `<input>` component.

https://github.com/OM-MediaWorks/bcp47-picker/assets/6933510/5423a5f5-67c3-4b73-8166-9e20bb813fdc

**Comment by danielbeeke** [comment]
Thanks for the detailed report.
